name: dynamic_theming
description: Dynamic theming in flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^1.2.5
  flutter_bloc: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_picture.jpeg
    - assets/images/wallpaper.jpg
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Yanone Kaffeesatz
      fonts:
        - asset: assets/fonts/YanoneKaffeesatz-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf